version: '3'
services:
  frontend:
    container_name: frontend
    image: img-frontend
    stdin_open: true
    ports:
      - "3000:3000"
      - "3010:3010"
    networks:
      - mern
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    container_name: backend
    image: img-backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    networks:
      - mern
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "8081:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
    
networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local